### ISSUE TITLE
Blurry content

### ISSUE THREAD

**Issue by Eschon** [mapshakers/leaflet-control-window#1]
When I open your [Demo](http://mapshakers.com/projects/leaflet-control-window/) in Chrome or Safari on OS X 10.10.5 the content of the window is blurry.

![screen shot 2015-09-14 at 13 31 28](https://cloud.githubusercontent.com/assets/11647830/9848817/ee057f66-5ae4-11e5-9cbe-4fc826854c93.png)

 Browser versions: Safari 8.0.8, Chrome 45.0.2454.85

**Comment by filipzava** [comment]
Thank you for opening this issue! It was caused by CSS `translate3d()`. Now this behavior was disabled as you can see. (same Chrome version). 
![leaflet-window](https://cloud.githubusercontent.com/assets/12759049/9850496/3bb58fa4-5af3-11e5-817f-d978dacba2e6.jpg)
Thx!
