### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by stevenvdbosch** [mapshakers/leaflet-control-window#15]
Clicking the icon gives:
`L.Control.Window.js:3 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at L.Control.Window.js:3`

Tried with chrome and Firefox.

**Comment by filipzava** [comment]
Thanks @stevenvdbosch. Leaflet was upgraded and Window plugin is now running. ;)

**Comment by Rafnuss** [comment]
Also, if I'm correct the demo on the github readme should be with upper case
`L.control.window -> L.Control.Window`
as in [](https://raw.githubusercontent.com/mapshakers/leaflet-control-window/master/src/L.Control.Window.js)

**Comment by stevenvdbosch** [comment]
Verified the demo and it now works, no error in console
