### ISSUE TITLE
Close button only to hide the window

### ISSUE THREAD

**Issue by a1an77** [mapshakers/leaflet-control-window#3]
Hi, I would like to keep the window available when the close button is clicked. To that extent I changed the code to just hide it. I think it would be good to have this as the default behavior ( in that case I have the simple patch ready to be pulled ).

A good way to destroy the window on close would be IMO to bind an event handler on onclose so that the user can decide if the window has to be reused (default) or destroyed (via handler).

Even better would be an option at creation time such as destroy_on_close : true 
Thoughts?

**Comment by filipzava** [comment]
Thanks, merged!
