### ISSUE TITLE
interact with map while control window is open

### ISSUE THREAD

**Issue by troddick** [mapshakers/leaflet-control-window#7]
Is it possible to have an option to be able to interact with the map while the control window is open? 

I am looking for a draggable modal with information on a point feature, that can be updated when different points are clicked. This comes so close to what I need. I'm building an angular2/leaflet app and need to open this control-window from a point click and also from outside the map area. First things first, I need something draggable and also allows interaction with the map while open.
Thanks!

**Comment by filipzava** [comment]
Hi, thanks for choosing **leaflet-control-window**. You can use non-modal window already. Just use modal option. Ex. `L.control.window(map, {title: 'Hello world!', maxWidth: 400, modal: false} );` and you should be able interact with map. Hope this is what you are looking for.
